# Render Blueprint for Python Group Project
# Deployment configuration for Flask app with PostgreSQL

services:
  # Web Service - Flask Application
  - type: web
    name: python-group-project
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: oregon
    branch: dev-main-updates
    healthCheckPath: /
    envVars:
      - key: FLASK_APP
        value: app
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: SCHEMA
        value: python_group_project
      - key: DATABASE_URL
        fromDatabase:
          name: python-group-project-db
          property: connectionString

# PostgreSQL Database
databases:
  - name: python-group-project-db
    plan: free
    region: oregon
    databaseName: python_group_project
    user: python_user